apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: os-service-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: os-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: fiap-tech-challenge/development/database/credentials
        property: DATABASE_URL
