apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: os-service
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /api/v1/health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/service-orders
            pathType: Prefix
            backend:
              service:
                name: os-service
                port:
                  number: 80
          - path: /api/v1/clients
            pathType: Prefix
            backend:
              service:
                name: os-service
                port:
                  number: 80
          - path: /api/v1/vehicles
            pathType: Prefix
            backend:
              service:
                name: os-service
                port:
                  number: 80
          - path: /api/v1/health
            pathType: Exact
            backend:
              service:
                name: os-service
                port:
                  number: 80
