apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - external-secret.yaml
  - serviceaccount.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: os-service
  app.kubernetes.io/part-of: fiap-tech-challenge
  app.kubernetes.io/managed-by: kustomize
